name: Testing Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        version: 1.2.7

    - name: Install dependencies
      run: bun install --ignore-scripts --frozen-lockfile

    - name: Run lint
      run: bun check

    - name: Run tests
      run: bun test